flags: {}
packages:
- '.'
- location:
    git: https://www.github.com/mattjbray/elm-export
    commit: 3dfafc7a717003ff4374119ff6f60e5b56868d8f
  extra-dep: True
- location:
    git: https://www.github.com/mattjbray/servant-elm
    commit: 342646d6f1ea9adf8886322f26abca5adfd8a48b
  extra-dep: True
extra-deps:
resolver: lts-7.5
